version: '3.8'

services:
  db:
    image: postgres:16
    container_name: linguins-postgres2
    environment:
      POSTGRES_DB: linguins
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d linguins"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - terminal-net

  ubuntu-terminal:
    image: ubuntu:22.04
    container_name: web-terminal-ubuntu
    hostname: web-terminal
    restart: always
    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - terminal-data:/root
    networks:
      - terminal-net

networks:
  terminal-net:
    driver: bridge

volumes:
  terminal-data: